export enum EAddressType {
  TYPE_CORSO = 'CORSO',
  TYPE_VIA = 'VIA',
  TYPE_VIALE = 'VIALE',
  TYPE_PIAZZALE = 'PIAZZALE',
  TYPE_PIAZZA = 'PIAZZA',
  TYPE_LUNGOMARE = 'LUNGOMARE',
  TYPE_LARGO = 'LARGO',
  TYPE_FONDO = 'FONDO',
  TYPE_VICOLO = 'VICOLO',
}
